# Generated by Django 3.1 on 2020-08-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
