# Generated by Django 3.1 on 2020-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_code',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
