# Generated by Django 3.1 on 2020-08-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='aboutline',
        ),
    ]
