# Generated by Django 3.1 on 2020-08-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200807_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
