# Generated by Django 3.1 on 2020-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecard',
            name='about',
            field=models.CharField(default='Some text', max_length=5000),
        ),
        migrations.AddField(
            model_name='imagecard',
            name='quote',
            field=models.CharField(default='Some text', max_length=5000),
        ),
    ]
