# Generated by Django 3.1 on 2020-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200807_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='Some text', max_length=5000)),
                ('quote', models.CharField(default='Some text', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagecard',
            name='about',
        ),
        migrations.RemoveField(
            model_name='imagecard',
            name='quote',
        ),
    ]
