# Generated by Django 3.1 on 2020-08-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200807_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='aboutline',
        ),
    ]
