# Generated by Django 3.1 on 2020-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=2048)),
                ('explanation_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('explanation_paragraph', models.CharField(blank=True, default=None, max_length=1400, null=True)),
            ],
        ),
    ]
