# Generated by Django 3.1 on 2020-08-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvideo',
            name='explanation_paragraph',
        ),
        migrations.RemoveField(
            model_name='newvideo',
            name='explanation_title',
        ),
    ]
