# Generated by Django 3.1 on 2020-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_auto_20200813_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvideo',
            name='explanation_paragraph',
            field=models.CharField(blank=True, default=None, max_length=1400, null=True),
        ),
        migrations.AddField(
            model_name='newvideo',
            name='explanation_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
