# Generated by Django 3.1 on 2020-08-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_auto_20200813_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.item')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.pack')),
            ],
        ),
        migrations.DeleteModel(
            name='NewVideo',
        ),
        migrations.AddField(
            model_name='pack',
            name='items',
            field=models.ManyToManyField(through='Video.PackItem', to='Video.Item'),
        ),
    ]
