# Generated by Django 3.1 on 2020-08-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0004_auto_20200814_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('parent', models.ManyToManyField(blank=True, default=None, related_name='_categories_parent_+', to='Video.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='pack',
            name='items',
        ),
        migrations.RemoveField(
            model_name='packitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='packitem',
            name='pack',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackItem',
        ),
    ]
