# Generated by Django 3.1 on 2020-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0007_auto_20200814_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, to='Video.Descriptions'),
        ),
    ]
