# Generated by Django 3.1 on 2020-08-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0011_auto_20200815_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_topic', models.CharField(max_length=100)),
                ('title1', models.CharField(max_length=100)),
                ('description_paragraph', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_title',
        ),
        migrations.RemoveField(
            model_name='description',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='description',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Video.information'),
        ),
    ]
