# Generated by Django 3.1 on 2020-08-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0016_auto_20200816_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='')),
                ('video_subtitle', models.CharField(max_length=100)),
                ('subtitle_explanation', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='newvideo',
            name='video_title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Explanation',
        ),
    ]
