# Generated by Django 3.1 on 2020-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0017_auto_20200819_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexplanation',
            name='background_image',
        ),
        migrations.AddField(
            model_name='newvideo',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
