# Generated by Django 3.1 on 2020-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0019_auto_20200819_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
