# Generated by Django 3.1 on 2020-08-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0020_morevideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoreVideos',
            new_name='MoreVideo',
        ),
    ]
