# Generated by Django 3.1 on 2020-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0021_auto_20200820_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='morevideo',
            name='video_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
