# Generated by Django 3.1 on 2020-08-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0022_morevideo_video_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morevideo',
            name='video_code',
            field=models.CharField(max_length=100),
        ),
    ]
