# Generated by Django 3.1 on 2020-08-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=32)),
                ('subtitle', models.CharField(max_length=60)),
                ('share_link', models.CharField(max_length=2048)),
            ],
        ),
    ]
